#!/bin/bash
#Copyright 2011 Anthony Youd/Newcastle University
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Compile and set up the code ready to run in a separate directory
# usage:  ./setup <directory name> <precision>

mkdir -p $1 2> /dev/null

#Compile.  Set j=nprocs+1 for efficient parallel make.
if [ $# -gt 1 ]; then
  if [ $2 == 'single' ]; then
    make -j 5 precision=single
  else
    echo ERROR: Invalid second argument.
    exit 1
  fi
else
  make -j 5
fi

#Setup dir
if [ $? == 0 ]; then
  mv gpe $1
  cp parameters.in run.in ic.in $1
  cp run.sh $1
  cd $1
fi
