#!/bin/bash
#
# Copyright (c) Anthony J. Youd/Newcastle University 2011
#
# Compile and set up the code ready to run in a separate directory
# usage:  ./setup <directory name> <precision>

mkdir -p $1 2> /dev/null

#Compile.  Set j=nprocs+1 for efficient parallel make.
if [ $# -gt 1 ]; then
  if [ $2 == 'single' ]; then
    make -j 5 precision=single
  else
    echo ERROR: Invalid second argument.
    exit 1
  fi
else
  make -j 5
fi

#Setup dir
if [ $? == 0 ]; then
  mv gpe $1
  cp parameters.in run.in ic.in $1
  cp run.sh $1
  cd $1
fi
